properties([
    parameters([
        string(
            defaultValue: 'dev',
            name: 'Environment'
        ),
        choice(
            choices: ['apply', 'plan', 'destroy'],
            name: 'Terraform_Action'
        )
    ])
])

pipeline {
    agent any

    environment {
        ARM_CLIENT_ID       = credentials('azure_client_id')
        ARM_CLIENT_SECRET   = credentials('azure-client-secret')
        ARM_TENANT_ID       = credentials('azure-tenant_id')
        ARM_SUBSCRIPTION_ID = credentials('azure-subscription-id')
        TF_DIR = "AKS-Terraform-GitHub-Actions/aks"
    }

    stages {

        stage('Preparing') {
            steps {
                echo "Selected Environment = ${params.Environment}"
                echo "Selected Action = ${params.Terraform_Action}"
            }
        }

        stage('Git Pulling') {
            steps {
                git branch: 'master',
                    credentialsId: 'github-token',
                    url: 'https://github.com/handgeg7-cpu/AKS-Terraform-GitHub-Actions.git'
            }
        }

        stage('Check Workspace Files') {
            steps {
                sh "pwd"
                sh "ls -la"
                sh "ls -la ${TF_DIR}"
            }
        }

        stage('Clean Terraform Cache') {
            steps {
                sh "rm -rf ${TF_DIR}/.terraform"
            }
        }

        stage('Terraform Init') {
            steps {
                sh "terraform -chdir=${TF_DIR} init"
            }
        }

        stage('Terraform Validate') {
            steps {
                sh "terraform -chdir=${TF_DIR} validate"
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.Terraform_Action == 'plan' }
            }
            steps {
                script {
                    sh "terraform -chdir=${TF_DIR} plan -var-file=${params.Environment}.tfvars"
                }
            }
        }

        stage('Terraform Apply') {
            when {
                expression { params.Terraform_Action == 'apply' }
            }
            steps {
                script {
                    sh "terraform -chdir=${TF_DIR} apply -var-file=${params.Environment}.tfvars -auto-approve"
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { params.Terraform_Action == 'destroy' }
            }
            steps {
                script {
                    sh "terraform -chdir=${TF_DIR} destroy -var-file=${params.Environment}.tfvars -auto-approve"
                }
            }
        }
    }
}